### ISSUE TITLE
Errors when upgrading from Kyma 1.24.8 to Kyma main

### ISSUE THREAD

**Issue by mfaizanse** [kyma-incubator/reconciler#399]
**Description**

I am getting reconciliation errors when trying to upgrade Kyma v1.24.8 to Kyma main.

**Steps to reproduce**

1. Provision a Kyma v1.24.8 cluster using:
```
kyma install --source 1.24.8
```
2. Upgrade using reconciler locally: (I have used commit: `fae1c8e453e6e1d549ce29bd42f05b24593ded15` of reconciler)
```
ISTIOCTL_PATH=/usr/local/bin/istioctl go run cmd/mothership/main.go local --kubeconfig=/path_to_kubeconfig.yml --value global.domainName=xxx.xxx.shoot.canary.k8s-hana.ondemand.com
```

**Error logs**
```
Error: reconciliation of 5 component(s) failed:
	- component 'logging' failed with status 'error': All attempts fail:
#1: StatefulSet.apps "logging-loki" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
#2: StatefulSet.apps "logging-loki" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
#3: StatefulSet.apps "logging-loki" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
#4: StatefulSet.apps "logging-loki" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
#5: StatefulSet.apps "logging-loki" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden

	- component 'monitoring' failed with status 'error': All attempts fail:
#1: PersistentVolumeClaim "monitoring-grafana" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
  	AccessModes:      {"ReadWriteOnce"},
  	Selector:         nil,
  	Resources:        {Requests: {s"storage": {i: {...}, s: "1Gi", Format: "BinarySI"}}},
- 	VolumeName:       "",
+ 	VolumeName:       "pv--f292c588-baec-40fe-91d3-a9341312fa32",
- 	StorageClassName: nil,
+ 	StorageClassName: &"default",
  	VolumeMode:       &"Filesystem",
  	DataSource:       nil,
  }

#2: PersistentVolumeClaim "monitoring-grafana" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
  	AccessModes:      {"ReadWriteOnce"},
  	Selector:         nil,
  	Resources:        {Requests: {s"storage": {i: {...}, s: "1Gi", Format: "BinarySI"}}},
- 	VolumeName:       "",
+ 	VolumeName:       "pv--f292c588-baec-40fe-91d3-a9341312fa32",
- 	StorageClassName: nil,
+ 	StorageClassName: &"default",
  	VolumeMode:       &"Filesystem",
  	DataSource:       nil,
  }

#3: PersistentVolumeClaim "monitoring-grafana" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
  	AccessModes:      {"ReadWriteOnce"},
  	Selector:         nil,
  	Resources:        {Requests: {s"storage": {i: {...}, s: "1Gi", Format: "BinarySI"}}},
- 	VolumeName:       "",
+ 	VolumeName:       "pv--f292c588-baec-40fe-91d3-a9341312fa32",
- 	StorageClassName: nil,
+ 	StorageClassName: &"default",
  	VolumeMode:       &"Filesystem",
  	DataSource:       nil,
  }

#4: PersistentVolumeClaim "monitoring-grafana" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
  	AccessModes:      {"ReadWriteOnce"},
  	Selector:         nil,
  	Resources:        {Requests: {s"storage": {i: {...}, s: "1Gi", Format: "BinarySI"}}},
- 	VolumeName:       "",
+ 	VolumeName:       "pv--f292c588-baec-40fe-91d3-a9341312fa32",
- 	StorageClassName: nil,
+ 	StorageClassName: &"default",
  	VolumeMode:       &"Filesystem",
  	DataSource:       nil,
  }

#5: PersistentVolumeClaim "monitoring-grafana" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
  	AccessModes:      {"ReadWriteOnce"},
  	Selector:         nil,
  	Resources:        {Requests: {s"storage": {i: {...}, s: "1Gi", Format: "BinarySI"}}},
- 	VolumeName:       "",
+ 	VolumeName:       "pv--f292c588-baec-40fe-91d3-a9341312fa32",
- 	StorageClassName: nil,
+ 	StorageClassName: &"default",
  	VolumeMode:       &"Filesystem",
  	DataSource:       nil,
  }


	- component 'serverless' failed with status 'error': All attempts fail:
#1: PersistentVolumeClaim "serverless-docker-registry" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
  	AccessModes:      {"ReadWriteOnce"},
  	Selector:         nil,
  	Resources:        {Requests: {s"storage": {i: {...}, s: "20Gi", Format: "BinarySI"}}},
- 	VolumeName:       "",
+ 	VolumeName:       "pv--1f481f27-2092-4410-b5cb-a8b5f732a445",
- 	StorageClassName: nil,
+ 	StorageClassName: &"default",
  	VolumeMode:       &"Filesystem",
  	DataSource:       nil,
  }

#2: PersistentVolumeClaim "serverless-docker-registry" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
  	AccessModes:      {"ReadWriteOnce"},
  	Selector:         nil,
  	Resources:        {Requests: {s"storage": {i: {...}, s: "20Gi", Format: "BinarySI"}}},
- 	VolumeName:       "",
+ 	VolumeName:       "pv--1f481f27-2092-4410-b5cb-a8b5f732a445",
- 	StorageClassName: nil,
+ 	StorageClassName: &"default",
  	VolumeMode:       &"Filesystem",
  	DataSource:       nil,
  }

#3: PersistentVolumeClaim "serverless-docker-registry" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
  	AccessModes:      {"ReadWriteOnce"},
  	Selector:         nil,
  	Resources:        {Requests: {s"storage": {i: {...}, s: "20Gi", Format: "BinarySI"}}},
- 	VolumeName:       "",
+ 	VolumeName:       "pv--1f481f27-2092-4410-b5cb-a8b5f732a445",
- 	StorageClassName: nil,
+ 	StorageClassName: &"default",
  	VolumeMode:       &"Filesystem",
  	DataSource:       nil,
  }

#4: PersistentVolumeClaim "serverless-docker-registry" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
  	AccessModes:      {"ReadWriteOnce"},
  	Selector:         nil,
  	Resources:        {Requests: {s"storage": {i: {...}, s: "20Gi", Format: "BinarySI"}}},
- 	VolumeName:       "",
+ 	VolumeName:       "pv--1f481f27-2092-4410-b5cb-a8b5f732a445",
- 	StorageClassName: nil,
+ 	StorageClassName: &"default",
  	VolumeMode:       &"Filesystem",
  	DataSource:       nil,
  }

#5: PersistentVolumeClaim "serverless-docker-registry" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
  	AccessModes:      {"ReadWriteOnce"},
  	Selector:         nil,
  	Resources:        {Requests: {s"storage": {i: {...}, s: "20Gi", Format: "BinarySI"}}},
- 	VolumeName:       "",
+ 	VolumeName:       "pv--1f481f27-2092-4410-b5cb-a8b5f732a445",
- 	StorageClassName: nil,
+ 	StorageClassName: &"default",
  	VolumeMode:       &"Filesystem",
  	DataSource:       nil,
  }


	- component 'rafter' failed with status 'error': All attempts fail:
#1: PersistentVolumeClaim "rafter-minio" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
  	AccessModes:      {"ReadWriteOnce"},
  	Selector:         nil,
  	Resources:        {Requests: {s"storage": {i: {...}, s: "10Gi", Format: "BinarySI"}}},
- 	VolumeName:       "",
+ 	VolumeName:       "pv--916d3dd7-2f77-4dfb-8319-d303c1891898",
- 	StorageClassName: nil,
+ 	StorageClassName: &"default",
  	VolumeMode:       &"Filesystem",
  	DataSource:       nil,
  }

#2: PersistentVolumeClaim "rafter-minio" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
  	AccessModes:      {"ReadWriteOnce"},
  	Selector:         nil,
  	Resources:        {Requests: {s"storage": {i: {...}, s: "10Gi", Format: "BinarySI"}}},
- 	VolumeName:       "",
+ 	VolumeName:       "pv--916d3dd7-2f77-4dfb-8319-d303c1891898",
- 	StorageClassName: nil,
+ 	StorageClassName: &"default",
  	VolumeMode:       &"Filesystem",
  	DataSource:       nil,
  }

#3: PersistentVolumeClaim "rafter-minio" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
  	AccessModes:      {"ReadWriteOnce"},
  	Selector:         nil,
  	Resources:        {Requests: {s"storage": {i: {...}, s: "10Gi", Format: "BinarySI"}}},
- 	VolumeName:       "",
+ 	VolumeName:       "pv--916d3dd7-2f77-4dfb-8319-d303c1891898",
- 	StorageClassName: nil,
+ 	StorageClassName: &"default",
  	VolumeMode:       &"Filesystem",
  	DataSource:       nil,
  }

#4: PersistentVolumeClaim "rafter-minio" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
  	AccessModes:      {"ReadWriteOnce"},
  	Selector:         nil,
  	Resources:        {Requests: {s"storage": {i: {...}, s: "10Gi", Format: "BinarySI"}}},
- 	VolumeName:       "",
+ 	VolumeName:       "pv--916d3dd7-2f77-4dfb-8319-d303c1891898",
- 	StorageClassName: nil,
+ 	StorageClassName: &"default",
  	VolumeMode:       &"Filesystem",
  	DataSource:       nil,
  }

#5: PersistentVolumeClaim "rafter-minio" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
  	AccessModes:      {"ReadWriteOnce"},
  	Selector:         nil,
  	Resources:        {Requests: {s"storage": {i: {...}, s: "10Gi", Format: "BinarySI"}}},
- 	VolumeName:       "",
+ 	VolumeName:       "pv--916d3dd7-2f77-4dfb-8319-d303c1891898",
- 	StorageClassName: nil,
+ 	StorageClassName: &"default",
  	VolumeMode:       &"Filesystem",
  	DataSource:       nil,
  }


	- component 'application-connector' failed with status 'error': All attempts fail:
#1: Job.batch "application-connector-certs-setup-job" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app.kubernetes.io/instance":"application-connector", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"application-connector", "helm.sh/chart":"application-connector-1.0.0", "release":"application-connector"}: `selector` does not match template `labels`, spec.selector: Invalid value: "null": field is immutable, spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"application-connector-certs-setup-job", GenerateName:"", Namespace:"kyma-integration", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"app.kubernetes.io/instance":"application-connector", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"application-connector", "helm.sh/chart":"application-connector-1.0.0", "release":"application-connector"}, Annotations:map[string]string{"sidecar.istio.io/inject":"“false”"}, OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:core.PodSpec{Volumes:[]core.Volume(nil), InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"application-connector-certs-setup-job", Image:"eu.gcr.io/kyma-project/application-connectivity-certs-setup-job:PR-11678", Command:[]string(nil), Args:[]string{"/appconnectivitycertssetupjob", "--connectorCertificateSecret=kyma-integration/connector-service-app-ca", "--caCertificateSecret=istio-system/kyma-gateway-certs-cacert", "--caCertificate=", "--caKey=", "--caCertificateSecretToMigrate=istio-system/app-connector-certs", "--caCertificateSecretKeysToMigrate=[\"cacert\"]", "--generatedValidityTime=92d"}, WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount(nil), VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), StartupProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(0xc0253b4660), Stdin:false, StdinOnce:false, TTY:false}}, EphemeralContainers:[]core.EphemeralContainer(nil), RestartPolicy:"OnFailure", TerminationGracePeriodSeconds:(*int64)(0xc02c766ed8), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"application-connector-certs-setup-job", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc02cd63100), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", SetHostnameAsFQDN:(*bool)(nil), Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), PreemptionPolicy:(*core.PreemptionPolicy)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), Overhead:core.ResourceList(nil), EnableServiceLinks:(*bool)(nil), TopologySpreadConstraints:[]core.TopologySpreadConstraint(nil)}}: field is immutable]
#2: Job.batch "application-connector-certs-setup-job" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app.kubernetes.io/instance":"application-connector", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"application-connector", "helm.sh/chart":"application-connector-1.0.0", "release":"application-connector"}: `selector` does not match template `labels`, spec.selector: Invalid value: "null": field is immutable, spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"application-connector-certs-setup-job", GenerateName:"", Namespace:"kyma-integration", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"app.kubernetes.io/instance":"application-connector", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"application-connector", "helm.sh/chart":"application-connector-1.0.0", "release":"application-connector"}, Annotations:map[string]string{"sidecar.istio.io/inject":"“false”"}, OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:core.PodSpec{Volumes:[]core.Volume(nil), InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"application-connector-certs-setup-job", Image:"eu.gcr.io/kyma-project/application-connectivity-certs-setup-job:PR-11678", Command:[]string(nil), Args:[]string{"/appconnectivitycertssetupjob", "--connectorCertificateSecret=kyma-integration/connector-service-app-ca", "--caCertificateSecret=istio-system/kyma-gateway-certs-cacert", "--caCertificate=", "--caKey=", "--caCertificateSecretToMigrate=istio-system/app-connector-certs", "--caCertificateSecretKeysToMigrate=[\"cacert\"]", "--generatedValidityTime=92d"}, WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount(nil), VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), StartupProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(0xc030fb5e00), Stdin:false, StdinOnce:false, TTY:false}}, EphemeralContainers:[]core.EphemeralContainer(nil), RestartPolicy:"OnFailure", TerminationGracePeriodSeconds:(*int64)(0xc00543d6d8), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"application-connector-certs-setup-job", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc03232aa00), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", SetHostnameAsFQDN:(*bool)(nil), Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), PreemptionPolicy:(*core.PreemptionPolicy)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), Overhead:core.ResourceList(nil), EnableServiceLinks:(*bool)(nil), TopologySpreadConstraints:[]core.TopologySpreadConstraint(nil)}}: field is immutable]
#3: Job.batch "application-connector-certs-setup-job" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app.kubernetes.io/instance":"application-connector", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"application-connector", "helm.sh/chart":"application-connector-1.0.0", "release":"application-connector"}: `selector` does not match template `labels`, spec.selector: Invalid value: "null": field is immutable, spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"application-connector-certs-setup-job", GenerateName:"", Namespace:"kyma-integration", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"app.kubernetes.io/instance":"application-connector", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"application-connector", "helm.sh/chart":"application-connector-1.0.0", "release":"application-connector"}, Annotations:map[string]string{"sidecar.istio.io/inject":"“false”"}, OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:core.PodSpec{Volumes:[]core.Volume(nil), InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"application-connector-certs-setup-job", Image:"eu.gcr.io/kyma-project/application-connectivity-certs-setup-job:PR-11678", Command:[]string(nil), Args:[]string{"/appconnectivitycertssetupjob", "--connectorCertificateSecret=kyma-integration/connector-service-app-ca", "--caCertificateSecret=istio-system/kyma-gateway-certs-cacert", "--caCertificate=", "--caKey=", "--caCertificateSecretToMigrate=istio-system/app-connector-certs", "--caCertificateSecretKeysToMigrate=[\"cacert\"]", "--generatedValidityTime=92d"}, WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount(nil), VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), StartupProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(0xc011ed8060), Stdin:false, StdinOnce:false, TTY:false}}, EphemeralContainers:[]core.EphemeralContainer(nil), RestartPolicy:"OnFailure", TerminationGracePeriodSeconds:(*int64)(0xc00ca55c68), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"application-connector-certs-setup-job", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc020426d00), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", SetHostnameAsFQDN:(*bool)(nil), Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), PreemptionPolicy:(*core.PreemptionPolicy)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), Overhead:core.ResourceList(nil), EnableServiceLinks:(*bool)(nil), TopologySpreadConstraints:[]core.TopologySpreadConstraint(nil)}}: field is immutable]
#4: Job.batch "application-connector-certs-setup-job" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app.kubernetes.io/instance":"application-connector", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"application-connector", "helm.sh/chart":"application-connector-1.0.0", "release":"application-connector"}: `selector` does not match template `labels`, spec.selector: Invalid value: "null": field is immutable, spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"application-connector-certs-setup-job", GenerateName:"", Namespace:"kyma-integration", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"app.kubernetes.io/instance":"application-connector", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"application-connector", "helm.sh/chart":"application-connector-1.0.0", "release":"application-connector"}, Annotations:map[string]string{"sidecar.istio.io/inject":"“false”"}, OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:core.PodSpec{Volumes:[]core.Volume(nil), InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"application-connector-certs-setup-job", Image:"eu.gcr.io/kyma-project/application-connectivity-certs-setup-job:PR-11678", Command:[]string(nil), Args:[]string{"/appconnectivitycertssetupjob", "--connectorCertificateSecret=kyma-integration/connector-service-app-ca", "--caCertificateSecret=istio-system/kyma-gateway-certs-cacert", "--caCertificate=", "--caKey=", "--caCertificateSecretToMigrate=istio-system/app-connector-certs", "--caCertificateSecretKeysToMigrate=[\"cacert\"]", "--generatedValidityTime=92d"}, WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount(nil), VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), StartupProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(0xc036d766c0), Stdin:false, StdinOnce:false, TTY:false}}, EphemeralContainers:[]core.EphemeralContainer(nil), RestartPolicy:"OnFailure", TerminationGracePeriodSeconds:(*int64)(0xc0383d64e8), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"application-connector-certs-setup-job", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc017bf0a80), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", SetHostnameAsFQDN:(*bool)(nil), Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), PreemptionPolicy:(*core.PreemptionPolicy)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), Overhead:core.ResourceList(nil), EnableServiceLinks:(*bool)(nil), TopologySpreadConstraints:[]core.TopologySpreadConstraint(nil)}}: field is immutable]
#5: Job.batch "application-connector-certs-setup-job" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app.kubernetes.io/instance":"application-connector", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"application-connector", "helm.sh/chart":"application-connector-1.0.0", "release":"application-connector"}: `selector` does not match template `labels`, spec.selector: Invalid value: "null": field is immutable, spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"application-connector-certs-setup-job", GenerateName:"", Namespace:"kyma-integration", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"app.kubernetes.io/instance":"application-connector", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"application-connector", "helm.sh/chart":"application-connector-1.0.0", "release":"application-connector"}, Annotations:map[string]string{"sidecar.istio.io/inject":"“false”"}, OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:core.PodSpec{Volumes:[]core.Volume(nil), InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"application-connector-certs-setup-job", Image:"eu.gcr.io/kyma-project/application-connectivity-certs-setup-job:PR-11678", Command:[]string(nil), Args:[]string{"/appconnectivitycertssetupjob", "--connectorCertificateSecret=kyma-integration/connector-service-app-ca", "--caCertificateSecret=istio-system/kyma-gateway-certs-cacert", "--caCertificate=", "--caKey=", "--caCertificateSecretToMigrate=istio-system/app-connector-certs", "--caCertificateSecretKeysToMigrate=[\"cacert\"]", "--generatedValidityTime=92d"}, WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount(nil), VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), StartupProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(0xc024c22180), Stdin:false, StdinOnce:false, TTY:false}}, EphemeralContainers:[]core.EphemeralContainer(nil), RestartPolicy:"OnFailure", TerminationGracePeriodSeconds:(*int64)(0xc0055e8578), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"application-connector-certs-setup-job", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc01018b380), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", SetHostnameAsFQDN:(*bool)(nil), Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), PreemptionPolicy:(*core.PreemptionPolicy)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), Overhead:core.ResourceList(nil), EnableServiceLinks:(*bool)(nil), TopologySpreadConstraints:[]core.TopologySpreadConstraint(nil)}}: field is immutable]
```

**Expected result**

Reconciliation should be successful. 

**Actual result**

Reconciliation failed.

**Troubleshooting**

**Comment by pxsalehi** [comment]
I have the same issue with a Kyma cluster from main (2be9f77c0), installed with Reconciler main (a3fbfa8) with a production profile. If I reconcile (from `main` to `main`), I get the following errors:
```
{"level":"INFO","time":"2021-11-12T14:21:58.377+0100","message":"Component 'monitoring' has status 'failed' (reason: PersistentVolumeClaim \"monitoring-grafana\" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims\n  core.PersistentVolumeClaimSpec{\n  \tAccessModes:      {\"ReadWriteOnce\"},\n  \tSelector:         nil,\n  \tResources:        {Requests: {s\"storage\": {i: {...}, s: \"1Gi\", Format: \"BinarySI\"}}},\n- \tVolumeName:       \"\",\n+ \tVolumeName:       \"pv--739407a2-d476-4e3c-8d78-886a30239f8e\",\n- \tStorageClassName: nil,\n+ \tStorageClassName: &\"default\",\n  \tVolumeMode:       &\"Filesystem\",\n  \tDataSource:       nil,\n  }\n)"}
{"level":"INFO","time":"2021-11-12T14:22:07.392+0100","message":"Component 'serverless' has status 'failed' (reason: PersistentVolumeClaim \"serverless-docker-registry\" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims\n  core.PersistentVolumeClaimSpec{\n  \tAccessModes:      {\"ReadWriteOnce\"},\n  \tSelector:         nil,\n  \tResources:        {Requests: {s\"storage\": {i: {...}, s: \"20Gi\", Format: \"BinarySI\"}}},\n- \tVolumeName:       \"\",\n+ \tVolumeName:       \"pv--8f54801b-6074-4883-9c99-81170571aec1\",\n- \tStorageClassName: nil,\n+ \tStorageClassName: &\"default\",\n  \tVolumeMode:       &\"Filesystem\",\n  \tDataSource:       nil,\n  }\n)"}
{"level":"INFO","time":"2021-11-12T14:22:07.409+0100","message":"Component 'rafter' has status 'failed' (reason: PersistentVolumeClaim \"rafter-minio\" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims\n  core.PersistentVolumeClaimSpec{\n  \tAccessModes:      {\"ReadWriteOnce\"},\n  \tSelector:         nil,\n  \tResources:        {Requests: {s\"storage\": {i: {...}, s: \"10Gi\", Format: \"BinarySI\"}}},\n- \tVolumeName:       \"\",\n+ \tVolumeName:       \"pv--9f765efd-d065-4a3e-a2e5-0b638c372aeb\",\n- \tStorageClassName: nil,\n+ \tStorageClassName: &\"default\",\n  \tVolumeMode:       &\"Filesystem\",\n  \tDataSource:       nil,\n  }\n)"}
...
{"level":"INFO","time":"2021-11-12T14:22:21.759+0100","message":"Component 'application-connector' has status 'failed' (reason: Job.batch \"application-connector-certs-setup-job\" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{\"app.kubernetes.io/instance\":\"application-connector\", \"app.kubernetes.io/managed-by\":\"Helm\", \"app.kubernetes.io/name\":\"application-connector\", \"helm.sh/chart\":\"application-connector-1.0.0\", \"release\":\"application-connector\"}: `selector` does not match template `labels`, spec.selector: Invalid value: \"null\": field is immutable, spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:\"application-connector-certs-setup-job\", GenerateName:\"\", Namespace:\"kyma-integration\", SelfLink:\"\", UID:\"\", ResourceVersion:\"\", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{\"app.kubernetes.io/instance\":\"application-connector\", \"app.kubernetes.io/managed-by\":\"Helm\", \"app.kubernetes.io/name\":\"application-connector\", \"helm.sh/chart\":\"application-connector-1.0.0\", \"release\":\"application-connector\"}, Annotations:map[string]string{\"sidecar.istio.io/inject\":\""false"\"}, OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:\"\", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:core.PodSpec{Volumes:[]core.Volume(nil), InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:\"application-connector-certs-setup-job\", Image:\"eu.gcr.io/kyma-project/application-connectivity-certs-setup-job:PR-11678\", Command:[]string(nil), Args:[]string{\"/appconnectivitycertssetupjob\", \"--connectorCertificateSecret=kyma-integration/connector-service-app-ca\", \"--caCertificateSecret=istio-system/kyma-gateway-certs-cacert\", \"--caCertificate=\", \"--caKey=\", \"--caCertificateSecretToMigrate=istio-system/app-connector-certs\", \"--caCertificateSecretKeysToMigrate=[\\\"cacert\\\"]\", \"--generatedValidityTime=92d\"}, WorkingDir:\"\", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount(nil), VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), StartupProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:\"/dev/termination-log\", TerminationMessagePolicy:\"File\", ImagePullPolicy:\"IfNotPresent\", SecurityContext:(*core.SecurityContext)(0xc011c83c80), Stdin:false, StdinOnce:false, TTY:false}}, EphemeralContainers:[]core.EphemeralContainer(nil), RestartPolicy:\"OnFailure\", TerminationGracePeriodSeconds:(*int64)(0xc021a6f918), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:\"ClusterFirst\", NodeSelector:map[string]string(nil), ServiceAccountName:\"application-connector-certs-setup-job\", AutomountServiceAccountToken:(*bool)(nil), NodeName:\"\", SecurityContext:(*core.PodSecurityContext)(0xc0114aca80), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:\"\", Subdomain:\"\", SetHostnameAsFQDN:(*bool)(nil), Affinity:(*core.Affinity)(nil), SchedulerName:\"default-scheduler\", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:\"\", Priority:(*int32)(nil), PreemptionPolicy:(*core.PreemptionPolicy)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), Overhead:core.ResourceList(nil), EnableServiceLinks:(*bool)(nil), TopologySpreadConstraints:[]core.TopologySpreadConstraint(nil)}}: field is immutable])"}
```

**Comment by mfaizanse** [comment]
solution will be proposed in: https://github.com/kyma-incubator/reconciler/issues/402

**Comment by pbochynski** [comment]
This should be resolved now.

**Comment by rakesh-garimella** [comment]
I can still reproduce the issue on my cluster
```
{"level":"INFO","time":"2021-11-16T16:20:58.065+0100","message":"Component 'logging' has status 'failed' (reason: StatefulSet.apps \"logging-loki\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden)"}
{"level":"INFO","time":"2021-11-16T16:20:58.128+0100","message":"Component 'logging' has status 'running'"}
{"level":"ERROR","time":"2021-11-16T16:21:01.803+0100","message":"Failed to apply Kubernetes unstructured entity: StatefulSet.apps \"logging-loki\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"}
{"level":"WARN","time":"2021-11-16T16:21:01.803+0100","message":"Failed to deploy manifests on target cluster: StatefulSet.apps \"logging-loki\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"}
{"level":"WARN","time":"2021-11-16T16:21:01.803+0100","message":"Runner: failing reconciliation of 'logging' in version 'main' with profile 'evaluation': StatefulSet.apps \"logging-loki\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"}
{"level":"INFO","time":"2021-11-16T16:21:01.803+0100","message":"Component 'logging' has status 'failed' (reason: StatefulSet.apps \"logging-loki\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden)"}
```

**Comment by tobiscr** [comment]
Ah, sorry - the filter of StatefulSets is not fixed yet. The last change was solving the issues when updating a clusterIP/nodePort-service, pods and PVCs. StatefulSets are not yet processed.

Wondering why it happens only during the upgrade. Tested today with reconciling Kyma 2.0 and StatefulSets were not causing issues.

     {"level":"DEBUG","time":"2021-11-16T23:38:34.643+0100","message":"Kubernetes resource 'KubernetesResource [Kind:StatefulSet,Namespace:kyma-system,Name:logging-loki]' successfully deployed"}
